"""
Interactive demo — show what Cogito actually does in practice.

Not a chat model. Not a text generator. This is a question-answering
reasoning layer on top of v14's learned Russian embeddings. You give
it facts ("Маша взяла яблоко", "Маша пошла в кухню"), it stores them,
you ask a question ("Где яблоко?"), it answers correctly by following
a chain of facts in its memory.

The answers are not generated by language model inference. They come
out of the reasoning block's iterative Unbind + cleanup loop — the
thing we've been validating all session.
"""

from __future__ import annotations

import numpy as np

from hdc_lang import HDCMemory, bind
from run_milestone_C import ReasoningBlock
from run_babi_task3 import Task3Reasoner
from run_milestone_F1 import load_v14_pool
from run_milestone_F2 import OrthogonalPretrainedCodebook


def make_reasoner(v14_pool):
    """Build a Task3Reasoner whose concept codebook is v14's orthogonal subset."""
    enc = Task3Reasoner(
        dim=v14_pool.shape[1],
        decay_holder=0.7,
        decay_location=0.8,
        decay_drop=0.8,
        seed=42,
    )
    enc.concepts = OrthogonalPretrainedCodebook(v14_pool, top_k=64, seed=42)
    enc.dropped_marker = enc.concepts.add(enc.DROPPED_NAME)
    return enc


def make_block(enc):
    return ReasoningBlock(
        concepts=enc.concepts,
        memories={
            "holder_of": enc.holder_of,
            "location_of": enc.location_of,
            "dropped_at": enc.dropped_at,
        },
        type_groups={"person": enc._people, "place": enc._places},
        max_iter=5,
    )


def print_header(title):
    print()
    print("=" * 72)
    print(f" {title}")
    print("=" * 72)


def run_scenario(name, events, questions, v14_pool):
    print_header(name)
    enc = make_reasoner(v14_pool)

    print("\nСистеме по одному даются факты:")
    for event in events:
        kind = event[0]
        if kind == "move":
            _, person, place = event
            print(f"  -> {person} пошёл в {place}.")
        elif kind == "pickup":
            _, person, obj = event
            print(f"  -> {person} взял {obj}.")
        elif kind == "drop":
            _, person, obj = event
            print(f"  -> {person} бросил {obj}.")
        enc.observe(event)

    block = make_block(enc)
    print("\nВопросы:")
    for q_obj, true_answer in questions:
        pred, iters = block.solve(q_obj, target_type="place")
        verdict = "OK" if pred == true_answer else "WRONG"
        expected_str = f" (ожидали: {true_answer})" if true_answer else ""
        print(f"  ? Где {q_obj}?  -> {pred}"
              f"  [за {iters} шагов рассуждения]  [{verdict}{expected_str}]")


def main():
    print("Loading v14 codebook...")
    v14_pool = load_v14_pool()
    print(f"  shape: {v14_pool.shape}, orthogonal subset will be built on the fly")

    # ---- Scenario 1: simple chain ----
    run_scenario(
        "Scenario 1 — простая цепочка",
        events=[
            ("pickup", "Маша", "яблоко"),
            ("move", "Маша", "кухня"),
        ],
        questions=[
            ("яблоко", "кухня"),
            ("Маша", "кухня"),
        ],
        v14_pool=v14_pool,
    )

    # ---- Scenario 2: multiple people, chain through one ----
    run_scenario(
        "Scenario 2 — несколько людей, вопрос про конкретного",
        events=[
            ("pickup", "Маша", "яблоко"),
            ("pickup", "Ваня", "мяч"),
            ("move", "Маша", "офис"),
            ("move", "Ваня", "сад"),
            ("move", "Катя", "спальня"),
        ],
        questions=[
            ("яблоко", "офис"),
            ("мяч", "сад"),
            ("Маша", "офис"),
            ("Ваня", "сад"),
            ("Катя", "спальня"),
        ],
        v14_pool=v14_pool,
    )

    # ---- Scenario 3: branching — drop breaks the chain ----
    run_scenario(
        "Scenario 3 — drop ломает цепочку (задача на branching)",
        events=[
            ("pickup", "Маша", "книга"),
            ("move", "Маша", "офис"),
            ("drop", "Маша", "книга"),
            ("move", "Маша", "кухня"),
        ],
        questions=[
            ("книга", "офис"),
            ("Маша", "кухня"),
        ],
        v14_pool=v14_pool,
    )

    # ---- Scenario 4: re-pickup — chain restored ----
    run_scenario(
        "Scenario 4 — перехват предмета другим человеком",
        events=[
            ("pickup", "Маша", "телефон"),
            ("move", "Маша", "офис"),
            ("pickup", "Ваня", "телефон"),
            ("move", "Ваня", "сад"),
        ],
        questions=[
            ("телефон", "сад"),
            ("Маша", "офис"),
            ("Ваня", "сад"),
        ],
        v14_pool=v14_pool,
    )

    # ---- Scenario 5: deep-ish chain + distractors ----
    run_scenario(
        "Scenario 5 — больше событий, проверка памяти",
        events=[
            ("move", "Маша", "кухня"),
            ("pickup", "Маша", "яблоко"),
            ("move", "Ваня", "спальня"),
            ("move", "Катя", "гараж"),
            ("pickup", "Ваня", "ключ"),
            ("move", "Маша", "библиотека"),
            ("move", "Катя", "офис"),
            ("pickup", "Катя", "блокнот"),
            ("move", "Ваня", "кладовая"),
        ],
        questions=[
            ("яблоко", "библиотека"),
            ("ключ", "кладовая"),
            ("блокнот", "офис"),
        ],
        v14_pool=v14_pool,
    )


if __name__ == "__main__":
    main()
